on: [push, pull_request]
name: CI
env:
  RKT_PKG: uuid
jobs:
  build:
    name: >-
      Build on Racket
      '${{
         format(
           '{0}{1}{2}',
           matrix.version,
           ((matrix.vm && ' ') || ''),
           matrix.vm
         )
       }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "stable"
          - "current"
          - "8.7" # Debian 12 Bookorm
          - "8.2" # Ubuntu 22.04
          - "8.0"
          - "7.9" # Debian 11 Bullseye
          - "7.7"
          - "7.6"
        vm: [ "" ] # default for the version
        include:
          - version: "current"
            vm: "BC"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.10
        with:
          version: ${{ matrix.version }}
          variant: ${{ matrix.vm }}
          architecture: "x64"
          distribution: "full"
      - name: Install Package and its Dependencies
        run: raco pkg install --auto --batch --name $RKT_PKG
      - name: Run Tests
        run: raco test -x -p $RKT_PKG
      - name: Check Package Dependencies
        run: raco setup --check-pkg-deps --pkgs $RKT_PKG
# ================================================================
# NOTES:
# ------
# Do I want `--unused-pkg-deps`?
# On Travis, I had this:
###after_success:
### - raco setup --check-pkg-deps --pkgs adjutor
### - raco pkg install --auto cover cover-coveralls
### - raco cover -b -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
