on: [push, pull_request]
name: CI
env:
  RKT_PKG: uuid
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}'"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version:
          - "stable"
          - "current"
          - "8.0"
          - "7.7"
          - "7.6"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.3.1
        with:
          version: ${{ matrix.racket-version }}
          architecture: "x64"
          distribution: "full"
      - name: Install Package and its Dependencies
        run: raco pkg install --auto --batch --name $RKT_PKG
      - name: Run Tests
        run: raco test -x -p $RKT_PKG
      - name: Check Package Dependencies
        run: raco setup --check-pkg-deps --pkgs $RKT_PKG
# ================================================================
# NOTES:
# ------
# Do I want `--unused-pkg-deps`?
# I would test `racket-variant: "BC"` if I required Racket 8.0.
# On Travis, I had this:
###after_success:
### - raco setup --check-pkg-deps --pkgs adjutor
### - raco pkg install --auto cover cover-coveralls
### - raco cover -b -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
